domain_path: C:\Users\Raul\Desktop\SSC_projects\ALU\vitis_code\platform\export\platform\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Apps\Vivado_2024\Vitis\2024.1\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
